import { Submission, Country, DetectionTypeCount, Stats } from "@/types";

const sampleImageUrl1 = "https://pathpulse-staging-uploads.sgp1.digitaloceanspaces.com/submissions/ee6ee473-3982-46db-be72-d64a4cb65c69/2026/03/02/e3f15738-a917-4fcc-a434-cfbc3143b618/frame_002_070251.jpg";
const sampleImageUrl2 = "https://pathpulse-staging-uploads.sgp1.digitaloceanspaces.com/submissions/ee6ee473-3982-46db-be72-d64a4cb65c69/2026/03/02/e3f15738-a917-4fcc-a434-cfbc3143b618/frame_001_070251.jpg";
const sampleImageUrl3 = "https://pathpulse-staging-uploads.sgp1.digitaloceanspaces.com/submissions/ee6ee473-3982-46db-be72-d64a4cb65c69/2026/03/02/e3f15738-a917-4fcc-a434-cfbc3143b618/frame_003_070251.jpg";
const sampleImageUrl4 = "https://pathpulse-staging-uploads.sgp1.digitaloceanspaces.com/submissions/ee6ee473-3982-46db-be72-d64a4cb65c69/2026/03/02/e3f15738-a917-4fcc-a434-cfbc3143b618/frame_004_070251.jpg";

export const INITIAL_SUBMISSIONS: Submission[] = [
    {
        id: "sub-101",
        account_id: "ee6ee473-3982-46db-be72-d64a4cb65c69",
        username: "aieyaan007",
        user_name: "Aieyaan Khan",
        user_country: "IN",
        user_banned: false,
        submission_type: "burst",
        detection_type: "license-plate",
        beats_earned: 0.10,
        latitude: 19.1225,
        longitude: 72.9294,
        captured_at: "2026-03-02T06:57:15.000Z",
        verification_status: "pending",
        verified_at: null,
        rejection_reason: null,
        frame_count: 4,
        country_code: "IN",
        primary_image_id: "img-101-1",
        processing_metadata: { resolution: "640x640", device_model: "iPhone 15 Pro" },
        created_at: "2026-03-02T07:02:51.565Z",
        video_asset: null,
        has_video: false,
        has_images: true,
        images: [
            {
                id: "img-101-1",
                submission_id: "sub-101",
                frame_index: 0,
                is_primary: true,
                image_url: sampleImageUrl1,
                thumbnail_url: sampleImageUrl1,
                latitude: 19.1225,
                longitude: 72.9294,
                captured_at: "2026-03-02T06:57:15.000Z",
                detection_data: { detections: [{ confidence: 0.94, detection_type: "license-plate" }] },
                image_metadata: null
            },
            {
                id: "img-101-2",
                submission_id: "sub-101",
                frame_index: 1,
                is_primary: false,
                image_url: sampleImageUrl2,
                thumbnail_url: sampleImageUrl2,
                latitude: 19.1225,
                longitude: 72.9294,
                captured_at: "2026-03-02T06:57:15.000Z",
                detection_data: { detections: [] },
                image_metadata: null
            },
            {
                id: "img-101-3",
                submission_id: "sub-101",
                frame_index: 2,
                is_primary: false,
                image_url: sampleImageUrl3,
                thumbnail_url: sampleImageUrl3,
                latitude: 19.1225,
                longitude: 72.9294,
                captured_at: "2026-03-02T06:57:15.000Z",
                detection_data: { detections: [] },
                image_metadata: null
            }
        ]
    },
    {
        id: "sub-102",
        account_id: "8f7311d4-42b1-4f91-8871-a83d7890fe31",
        username: "rajesh_scout",
        user_name: "Rajesh Sharma",
        user_country: "IN",
        user_banned: false,
        submission_type: "burst",
        detection_type: "without_helmet",
        beats_earned: 0.25,
        latitude: 28.6139,
        longitude: 77.2090,
        captured_at: "2026-03-03T11:20:00.000Z",
        verification_status: "verified",
        verified_at: "2026-03-03T12:00:00.000Z",
        rejection_reason: null,
        frame_count: 2,
        country_code: "IN",
        primary_image_id: "img-102-1",
        processing_metadata: { resolution: "1280x720", device_model: "OnePlus 12" },
        created_at: "2026-03-03T11:25:30.000Z",
        video_asset: null,
        has_video: false,
        has_images: true,
        images: [
            {
                id: "img-102-1",
                submission_id: "sub-102",
                frame_index: 0,
                is_primary: true,
                image_url: sampleImageUrl2,
                thumbnail_url: sampleImageUrl2,
                latitude: 28.6139,
                longitude: 77.2090,
                captured_at: "2026-03-03T11:20:00.000Z",
                detection_data: { detections: [{ confidence: 0.88, detection_type: "without_helmet" }] },
                image_metadata: null
            },
            {
                id: "img-102-2",
                submission_id: "sub-102",
                frame_index: 1,
                is_primary: false,
                image_url: sampleImageUrl3,
                thumbnail_url: sampleImageUrl3,
                latitude: 28.6139,
                longitude: 77.2090,
                captured_at: "2026-03-03T11:20:00.000Z",
                detection_data: { detections: [] },
                image_metadata: null
            }
        ]
    },
    {
        id: "sub-103",
        account_id: "3e5900a1-77b3-46ea-9a84-190f8451bc02",
        username: "priya_m",
        user_name: "Priya Menon",
        user_country: "IN",
        user_banned: false,
        submission_type: "burst",
        detection_type: "lane",
        beats_earned: 0.15,
        latitude: 12.9716,
        longitude: 77.5946,
        captured_at: "2026-03-04T08:14:00.000Z",
        verification_status: "pending",
        verified_at: null,
        rejection_reason: null,
        frame_count: 3,
        country_code: "IN",
        primary_image_id: "img-103-1",
        processing_metadata: { resolution: "1920x1080", device_model: "Samsung S24" },
        created_at: "2026-03-04T08:20:10.000Z",
        video_asset: null,
        has_video: false,
        has_images: true,
        images: [
            {
                id: "img-103-1",
                submission_id: "sub-103",
                frame_index: 0,
                is_primary: true,
                image_url: sampleImageUrl3,
                thumbnail_url: sampleImageUrl3,
                latitude: 12.9716,
                longitude: 77.5946,
                captured_at: "2026-03-04T08:14:00.000Z",
                detection_data: { detections: [{ confidence: 0.91, detection_type: "lane" }] },
                image_metadata: null
            },
            {
                id: "img-103-2",
                submission_id: "sub-103",
                frame_index: 1,
                is_primary: false,
                image_url: sampleImageUrl4,
                thumbnail_url: sampleImageUrl4,
                latitude: 12.9716,
                longitude: 77.5946,
                captured_at: "2026-03-04T08:14:00.000Z",
                detection_data: { detections: [] },
                image_metadata: null
            }
        ]
    },
    {
        id: "sub-104",
        account_id: "7d1245ee-51ff-4318-8f81-55c2fbc94477",
        username: "alex_rider",
        user_name: "Alex Rider",
        user_country: "US",
        user_banned: false,
        submission_type: "video",
        detection_type: "vehicle",
        beats_earned: 0.50,
        latitude: 37.7749,
        longitude: -122.4194,
        captured_at: "2026-03-05T15:45:00.000Z",
        verification_status: "verified",
        verified_at: "2026-03-05T16:10:00.000Z",
        rejection_reason: null,
        frame_count: 1,
        country_code: "US",
        primary_image_id: null,
        processing_metadata: { resolution: "1080p", duration: "12s" },
        created_at: "2026-03-05T15:50:00.000Z",
        video_asset: {
            url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
            thumbnail_url: sampleImageUrl1
        },
        has_video: true,
        has_images: false,
        images: []
    },
    {
        id: "sub-105",
        account_id: "bb447711-231a-4c2f-b442-789a66d0ef01",
        username: "vikram_r",
        user_name: "Vikram Rao",
        user_country: "IN",
        user_banned: false,
        submission_type: "burst",
        detection_type: "DHelmet",
        beats_earned: 0.20,
        latitude: 13.0827,
        longitude: 80.2707,
        captured_at: "2026-03-06T09:12:00.000Z",
        verification_status: "pending",
        verified_at: null,
        rejection_reason: null,
        frame_count: 2,
        country_code: "IN",
        primary_image_id: "img-105-1",
        processing_metadata: { resolution: "720p", device_model: "Pixel 8" },
        created_at: "2026-03-06T09:15:30.000Z",
        video_asset: null,
        has_video: false,
        has_images: true,
        images: [
            {
                id: "img-105-1",
                submission_id: "sub-105",
                frame_index: 0,
                is_primary: true,
                image_url: sampleImageUrl4,
                thumbnail_url: sampleImageUrl4,
                latitude: 13.0827,
                longitude: 80.2707,
                captured_at: "2026-03-06T09:12:00.000Z",
                detection_data: { detections: [{ confidence: 0.96, detection_type: "DHelmet" }] },
                image_metadata: null
            }
        ]
    },
    {
        id: "sub-106",
        account_id: "9c339900-55aa-44bb-88cc-112233445566",
        username: "sam_drive",
        user_name: "Samantha Green",
        user_country: "GB",
        user_banned: false,
        submission_type: "burst",
        detection_type: "license-plate",
        beats_earned: 0.10,
        latitude: 51.5074,
        longitude: -0.1278,
        captured_at: "2026-03-07T14:30:00.000Z",
        verification_status: "rejected",
        verified_at: null,
        rejection_reason: "Blurry or unreadable plate numbers",
        frame_count: 2,
        country_code: "GB",
        primary_image_id: "img-106-1",
        processing_metadata: { resolution: "640x640", device_model: "iPhone 14" },
        created_at: "2026-03-07T14:35:00.000Z",
        video_asset: null,
        has_video: false,
        has_images: true,
        images: [
            {
                id: "img-106-1",
                submission_id: "sub-106",
                frame_index: 0,
                is_primary: true,
                image_url: sampleImageUrl1,
                thumbnail_url: sampleImageUrl1,
                latitude: 51.5074,
                longitude: -0.1278,
                captured_at: "2026-03-07T14:30:00.000Z",
                detection_data: { detections: [{ confidence: 0.42, detection_type: "license-plate" }] },
                image_metadata: null
            }
        ]
    },
    {
        id: "sub-107",
        account_id: "5a6b7c8d-9e0f-1a2b-3c4d-5e6f7a8b9c0d",
        username: "kavita_p",
        user_name: "Kavita Patel",
        user_country: "IN",
        user_banned: false,
        submission_type: "burst",
        detection_type: "without_helmet",
        beats_earned: 0.30,
        latitude: 23.0225,
        longitude: 72.5714,
        captured_at: "2026-03-08T10:05:00.000Z",
        verification_status: "pending",
        verified_at: null,
        rejection_reason: null,
        frame_count: 3,
        country_code: "IN",
        primary_image_id: "img-107-1",
        processing_metadata: { resolution: "1080p", device_model: "Vivo X90" },
        created_at: "2026-03-08T10:10:00.000Z",
        video_asset: null,
        has_video: false,
        has_images: true,
        images: [
            {
                id: "img-107-1",
                submission_id: "sub-107",
                frame_index: 0,
                is_primary: true,
                image_url: sampleImageUrl2,
                thumbnail_url: sampleImageUrl2,
                latitude: 23.0225,
                longitude: 72.5714,
                captured_at: "2026-03-08T10:05:00.000Z",
                detection_data: { detections: [{ confidence: 0.89, detection_type: "without_helmet" }] },
                image_metadata: null
            }
        ]
    },
    {
        id: "sub-108",
        account_id: "11223344-5566-7788-99aa-bbccddeeff00",
        username: "arjun_k",
        user_name: "Arjun Kapoor",
        user_country: "IN",
        user_banned: false,
        submission_type: "burst",
        detection_type: "vehicle",
        beats_earned: 0.15,
        latitude: 17.3850,
        longitude: 78.4867,
        captured_at: "2026-03-09T16:18:00.000Z",
        verification_status: "verified",
        verified_at: "2026-03-09T17:00:00.000Z",
        rejection_reason: null,
        frame_count: 2,
        country_code: "IN",
        primary_image_id: "img-108-1",
        processing_metadata: { resolution: "1080p", device_model: "Samsung Galaxy" },
        created_at: "2026-03-09T16:22:00.000Z",
        video_asset: null,
        has_video: false,
        has_images: true,
        images: [
            {
                id: "img-108-1",
                submission_id: "sub-108",
                frame_index: 0,
                is_primary: true,
                image_url: sampleImageUrl3,
                thumbnail_url: sampleImageUrl3,
                latitude: 17.3850,
                longitude: 78.4867,
                captured_at: "2026-03-09T16:18:00.000Z",
                detection_data: { detections: [{ confidence: 0.95, detection_type: "vehicle" }] },
                image_metadata: null
            }
        ]
    }
];

export const INITIAL_COUNTRIES: Country[] = [
    { country_code: "IN", country_name: "India", count: 6 },
    { country_code: "US", country_name: "United States", count: 1 },
    { country_code: "GB", country_name: "United Kingdom", count: 1 }
];

export const INITIAL_DETECTION_TYPES: DetectionTypeCount[] = [
    { detection_type: "license-plate", total: 2, pending: 1 },
    { detection_type: "without_helmet", total: 2, pending: 2 },
    { detection_type: "DHelmet", total: 1, pending: 1 },
    { detection_type: "lane", total: 1, pending: 1 },
    { detection_type: "vehicle", total: 2, pending: 0 }
];

export const INITIAL_STATS: Stats = {
    total_submissions: 8,
    verified: 3,
    rejected: 1,
    pending: 4,
    total_frames: 21,
    total_videos: 1,
    detection_types: [
        { detection_type: "license-plate", count: 2 },
        { detection_type: "without_helmet", count: 2 },
        { detection_type: "DHelmet", count: 1 },
        { detection_type: "lane", count: 1 },
        { detection_type: "vehicle", count: 2 }
    ]
};
